# SPDX-License-Identifier: BUSL-1.1
# Copyright (c) 2026 Maximilian Kaufmann. See LICENSE (Business Source License 1.1).

"""GET /internal/files/{storage_path} — serve a stored attachment or export.

v1.25.4 — closes the long-standing gap that left signed URLs un-routed.
Previously `DownloadAttachment` generated a `/internal/files/...?sig=...`
URL but no service implemented the path; nginx fell through to the SPA
catch-all and served `index.html` as the «PDF», so the user got an .html
file masqueraded with a .pdf extension and could not open it.

Behaviour:
  • Signature verified against ``LOTSMAN_SIGNED_URL_KEY`` (HMAC-SHA256).
  • Expiry checked (60s TTL on issue).
  • `Content-Type` from `registry.attachments.mime_type` (matches what
    upload-time sniffer recorded).
  • `Content-Disposition: inline; filename*=UTF-8''<urlencoded>` — `inline`
    so PDFs and images preview natively; browsers that can't render the
    type (Office) still get a Save dialog with the correct filename.
  • Cache-Control: no-store — signed URLs are short-lived and per-actor.

NOT mounted under `/api/v1` because (a) the URL is generated by the
storage layer to a fixed path that is *not* a public API contract, and
(b) skipping the `/api/v1` prefix matches the path baked into
`make_signed_url` since day one.
"""

from __future__ import annotations

import re
import uuid
from pathlib import Path
from urllib.parse import quote

import structlog
from fastapi import APIRouter, HTTPException, Query, Request
from fastapi.responses import FileResponse

from registry_service.api.deps import DbSession
from registry_service.infrastructure.db.repositories import (
    SqlAttachmentRepository,
    SqlExportJobRepository,
)
from registry_service.infrastructure.storage.signed_url import verify_signed_url

log = structlog.get_logger(__name__)

router = APIRouter(tags=["internal-files"])

# storage_path shape (current LocalFilesystemStorage layout):
#   attachments/<YYYY>/<MM>/<uuid>.<ext>
#   exports/<YYYY>/<MM>/<uuid>.xlsx
_UUID_FROM_PATH = re.compile(
    r"^(?P<kind>attachments|exports)/\d{4}/\d{2}/"
    r"(?P<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})"
    r"\.[A-Za-z0-9]+$"
)


def _format_content_disposition(filename: str) -> str:
    """Build a RFC 5987–compliant Content-Disposition header value.

    `inline` makes the browser preview the file (PDF / image) when it can;
    Office formats still trigger Save, but with the correct filename.
    `filename*=UTF-8''<encoded>` carries non-ASCII safely; the legacy
    `filename=` parameter is omitted to avoid mojibake on older clients.
    """
    encoded = quote(filename, safe="")
    return f"inline; filename*=UTF-8''{encoded}"


@router.get("/internal/files/{storage_path:path}", include_in_schema=False)
async def serve_signed_file(
    storage_path: str,
    request: Request,
    session: DbSession,
    expires: int = Query(...),
    sig: str = Query(...),
    type: str = Query(default="attachment"),
) -> FileResponse:
    if type not in {"attachment", "export"}:
        raise HTTPException(status_code=400, detail="Invalid resource type")

    m = _UUID_FROM_PATH.match(storage_path)
    if m is None:
        raise HTTPException(status_code=400, detail="Malformed storage path")

    kind = m.group("kind")
    expected_kind = "attachments" if type == "attachment" else "exports"
    if kind != expected_kind:
        raise HTTPException(status_code=400, detail="Path/type mismatch")

    try:
        resource_id = uuid.UUID(m.group("uuid"))
    except ValueError as exc:
        raise HTTPException(status_code=400, detail="Malformed resource id") from exc

    if not verify_signed_url(resource_id=str(resource_id), expires_unix=expires, sig=sig):
        raise HTTPException(status_code=403, detail="Signature invalid or expired")

    # Resolve filename + MIME from DB so the user sees the original upload
    # name rather than the UUID-named storage_path.
    if type == "attachment":
        repo = SqlAttachmentRepository(session)
        attachment = await repo.get_by_id(resource_id)
        if attachment is None:
            raise HTTPException(status_code=404, detail="Attachment not found")
        filename = attachment.original_filename
        media_type = attachment.mime_type or "application/octet-stream"
    else:
        exp_repo = SqlExportJobRepository(session)
        job = await exp_repo.get_by_id(resource_id)
        if job is None or job.file_path is None:
            raise HTTPException(status_code=404, detail="Export not found")
        filename = Path(job.file_path).name
        media_type = (
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )

    settings = request.app.state.settings
    volume_root = Path(settings.attachments_volume_root)
    full = volume_root / storage_path
    if not full.is_file():
        # Race with concurrent delete or volume mis-mount — surface as 404.
        log.warning("signed_file_missing_on_disk", storage_path=storage_path)
        raise HTTPException(status_code=404, detail="File not found on disk")

    return FileResponse(
        path=str(full),
        media_type=media_type,
        headers={
            "Content-Disposition": _format_content_disposition(filename),
            "Cache-Control": "no-store",
            "X-Content-Type-Options": "nosniff",
        },
    )
